---
title: "buques_port_BCN"
output: html_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
library(tidyverse)
library(jsonlite)
```



El [Port de Barcelona](https://opendata.portdebarcelona.cat/es/dataset/arribades-i-sortides-previstes-per-avui) publica cada dia un archivo que recoge las llegadas previstas y en otro las salidas previstas. Este script los baja cada dia. 

```{r llegadas}

prev_llegadas_BCN <- read_csv("https://opendata.portdebarcelona.cat/dataset/342fe09b-017b-4019-a743-ee773f09befd/resource/72f0fc9e-b4b4-4a61-a0fb-e7b65b601b4d/download/arribadesavui.csv")

write_csv(prev_llegadas_BCN, paste0("data/llegadas_previstas/prev_llegadas_BCN_", today(), ".csv"))

```


```{r salidas}

prev_salidas_BCN <- read_csv("https://opendata.portdebarcelona.cat/dataset/342fe09b-017b-4019-a743-ee773f09befd/resource/4bf1ccd0-5132-4d54-81d4-1ab72d5542e9/download/sortidesavui.csv")

write_csv(prev_salidas_BCN, paste0("data/salidas_previstas/prev_salidas_BCN_", today(), ".csv"))

```
